[project]
name = "rpa-sap"
version = "1.2.7"
description = "SAPGUI scripting automation"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "pywin32>=311",
    "wmi>=1.5.1",
]

[dependency-groups]
dev = [
    "black>=25.9.0",
    "pytest>=8.4.2",
]
