[project]
name = "rpa-sap"
version = "2.0.1"
description = "A comprehensive Python library for robust SAP GUI automation and RFC integration, designed for RPA workflows."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Grzegorz Zioło" }
]
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "python-dotenv>=1.2.2",
    "pywin32>=311",
    "wmi>=1.5.1",
]

[dependency-groups]
dev = [
    "black>=25.9.0",
    "pytest>=8.4.2",
]
